server:
  port: 9005


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


alibaba:
  cloud:
    access-key: xxx         # 不可提交!!!
    secret-key: xxx         # 不可提交!!!
    oss:
      endpoint: xxx         # 不可提交!!!
    bucket-name: xxx        # 不可提交!!!

