server:
  port: 10000


spring:
  # database(windows)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sa_token?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xia0yu

  # date-format
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  # redis
  redis:
    database: 3
    host: 127.0.0.1
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        max-idle: 10
        min-idle: 2
        max-wait: -1

  # mvc(Swagger2)
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


# mybatis-plus log
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 扫描实体类所在的包，这样在mapper.xml文件中就不用配置实体类全路径，直接写类名就行（xml没有使用）
  type-aliases-package: com.benjamin.entities


sa-token:
  # token前缀
  token-prefix: Bearer
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 3600 # 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false  # true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-128 # uuid
  # 是否输出操作日志
  is-log: true