server:
  port: 9007

spring:
  # database(windows)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xia0yu

  # date-format
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  # mvc(Swagger2)
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # rabbitMQ
  rabbitmq:
    host: 0.0.0.0
    port: 5672
    username: xxx
    password: 123456
    virtual-host: /